---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./infrastructure/metallb/prod/metallb
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: metallb
  targetNamespace: metallb-system
  timeout: 3m0s
  wait: true
