apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresspool-prod-cluster
  namespace: metallb-system
spec:
  addresses:
    # - 10.0.10.2/32
    - 192.168.100.11-192.168.100.15

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-addresspool-prod-cluster