---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: transformers
  namespace: flux-system
spec:
  interval: 30m0s
  path: "./k8s"
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: transformers
  targetNamespace: default
  timeout: 3m0s
  wait: true
