---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./applications/monitoring
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: monitoring
  targetNamespace: monitoring
  timeout: 3m0s
  wait: true
