---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/terrameijar/homelab
  ignore: |
    # Exclude all
    /*
    # include the metallb directory
    !/infrastructure/metallb
    # Exclude non kubernetes YAMLs
    /infrastructure/metallb**.yamllint.yaml
