---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 2m0s
  ref:
    branch: main
  url: ssh://git@github.com/terrameijar/homelab.git
  secretRef:
    name: flux-github-secret
