apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-ssm-test-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: production-test-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /K8s/Clusters/Prod/AnotherTest