apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        secretRef:
          accessKeyIdSecretRef:
            name: staging-aws-ssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: staging-aws-ssm-secret
            key: secret-access-key