apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-external-secret
  namespace: cert-manager
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: /K8s/Clusters/Prod/Cloudflare/cloudflare-api-token
        property: cloudflare-api-token
