apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring-stack
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '72.4.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 10m
  values:
    grafana:
      adminPassword: SuperSecurePassword
      service:
        type: ClusterIP
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
        hosts:
          - grafana.vuyisile.lan
        path: /
        pathType: Prefix
        ingressClassName: nginx
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false