---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: planka-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: planka-secret
    creationPolicy: Owner
  data:
    - secretKey: secretkey
      remoteRef:
        key: /K8s/Clusters/Prod/Planka/planka-secretkey
        property: SECRET_KEY

    - secretKey: planka-db-username
      remoteRef:
        key: /K8s/Clusters/Prod/Planka/planka-postgres
        property: username

    - secretKey: planka-db-password
      remoteRef:
        key: /K8s/Clusters/Prod/Planka/planka-postgres
        property: password

    - secretKey: planka-db-name
      remoteRef:
        key: /K8s/Clusters/Prod/Planka/planka-postgres
        property: database