# paperless-secrets.yaml
## The Secret is now managed by ExternalSecret. The actual data will be synced from the external source.
# apiVersion: v1
# kind: Secret
# metadata:
#   name: paperless-secrets
#   labels:
#     app: paperless
# stringData:
#   db_user: paperless
#   db_pass: changeme
#   secret_key: <managed-by-external-secret>

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: paperless-secrets
    creationPolicy: Owner
  data:
    - secretKey: db_user
      remoteRef:
        key: /K8s/Clusters/Staging/Paperless/db-creds
        property: db_user
    - secretKey: db_pass
      remoteRef:
        key: /K8s/Clusters/Staging/Paperless/db-creds
        property: db_pass
    - secretKey: secret_key
      remoteRef:
        key: /K8s/Clusters/Staging/Paperless/secret-key
        property: secret_key