apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wallabag-tls
  namespace: default
spec:
  secretName: wallabag-prod-cert-tls-secret
  issuerRef:
    name: cloudflare-letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "wallabag.ndlovucloud.co.zw"
