apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-tls-staging
  namespace: cert-manager
spec:
  secretName: pgadmin-staging-cert-tls-secret1
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - 'staging-pgadmin.vndprojects.com'