apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-tls
  namespace: cert-manager
spec:
  secretName: pgadmin-staging-cert-tls-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - 'pgadmin-staging.vndprojects.com'