apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: planka
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/planka
      version: "1.0.3"
      sourceRef:
        kind: GitRepository
        name: planka
        namespace: flux-system
      interval: 60m
  valuesFrom:
    - kind: Secret
      name: planka-secret
      valuesKey: secretkey
      targetPath: secretkey
  values:
    base:
      baseUrl: "https://planka.vndprojects.com"
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: planka.vndprojects.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - planka.vndprojects.com
          secretName: planka-tls
    
    postgresql:
      enabled: true
      auth:
        username: planka
        password: planka-password
        database: planka
    redis:
      enabled: true