apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: planka
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: master
  url: https://github.com/plankanban/planka.git