apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: planka
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: planka
      version: "1.0.3"
      sourceRef:
        kind: HelmRepository
        name: planka
        namespace: flux-system
      interval: 60m
  valuesFrom:
    - kind: Secret
      name: planka-secret
      valuesKey: secretkey
      targetPath: secretkey
  values:
    base:
      baseUrl: "https://planka.vndprojects.com"
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: planka.vndprojects.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - planka.vndprojects.com
          secretName: planka-tls
    
    postgresql:
      enabled: true
      auth:
        username: planka
        password: planka-password
        database: planka
    redis:
      enabled: true
    
    # Admin user
    admin_email: "demo@demo.demo" # Do not remove if you want to prevent this user from being edited/deleted
    admin_password: "demo"
    admin_name: "Demo Demo"
    admin_username: "demo"