apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatinsights-user
  namespace: chat-insights
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chatinsights-read-only
  namespace: chat-insights
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chatinsights-namespace-viewer
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chatinsights-read-only-cluster-binding
subjects:
  - kind: ServiceAccount
    name: chatinsights-user
    namespace: chat-insights
roleRef:
  kind: ClusterRole
  name: chatinsights-namespace-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chatinsights-read-only-binding
  namespace: chat-insights
subjects:
  - kind: ServiceAccount
    name: chatinsights-user
    namespace: chat-insights
roleRef:
  kind: Role
  name: chatinsights-read-only
  apiGroup: rbac.authorization.k8s.io
