---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chatinsights
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: chatinsights
  targetNamespace: chat-insights
  timeout: 3m0s
  wait: true
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: chat-insights
          namespace: chat-insights
        spec:
          replicas: 2
          template:
            spec:
              containers:
              - name: chat-insights
                image: andilejaden/chatinsight:sha-7da1649
