---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chatinsights
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: chatinsights
  targetNamespace: chatinsights
  timeout: 3m0s
  wait: true
