---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chatinsights
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: chatinsights
  targetNamespace: chat-insights
  timeout: 3m0s
  wait: true
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: chat-insights
          namespace: chat-insights
        spec:
          replicas: 1
          template:
            spec:
              containers:
              - name: chat-insights
                image: andilejaden/chatinsight:sha-b7ef52e
    - patch: |-
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: chat-insights
          namespace: chat-insights
          annotations:
            gethomepage.dev/description: Dynamically Detected Chat Insights
            gethomepage.dev/enabled: "true"
            gethomepage.dev/group: Cluster Management
            gethomepage.dev/name: Chat Insights
            nginx.ingress.kubernetes.io/rewrite-target: /$1