apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/production/apps/paperless-ngx
  prune: true
  sourceRef:
    kind: GitRepository
    name: paperless
  targetNamespace: default