apiVersion: v1
kind: Service
metadata:
  name: podinfo-lb
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: podinfo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
  type: LoadBalancer
