---
apiVersion: v1
kind: Service
metadata:
  name: paperless-postgres-svc
  namespace: default
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  clusterIP: None  # Headless service
  selector:
    app: postgres