---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: 
          ports:
            - containerPort: 80
          envFrom:
            -secretRef:
              - name: pgadmin-secret
                key: PGADMIN_DEFAULT_EMAIL
              - name: pgadmin-secret
                key: PGADMIN_DEFAULT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: superset-service
  namespace: default
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80