apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: route53-credentials-external-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: route53-credentials-secret
    creationPolicy: Owner
  data:
    - secretKey:  access-key
      remoteRef:
        key: /K8s/Clusters/Prod/AWS-User-AccessKeyID

    - secretKey: secret-access-key
      remoteRef:
        key: /K8s/Clusters/Prod/AWS-User-SecretAccessKey