apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-tls-staging
  namespace: cert-manager
spec:
  secretName: pgadmin-staging-cert-tls-secret
  issuerRef:
    name: cloudflare-letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - 'pgadmin.ndlovucloud.co.zw'