apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-external-secret
  namespace: default
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: /K8s/Clusters/Prod/pgadmin-credentials 
        property: PGADMIN_DEFAULT_EMAIL

    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: /K8s/Clusters/Prod/pgadmin-credentials
        property: PGADMIN_DEFAULT_PASSWORD