apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
    - key: /K8s/Clusters/Prod/pgadmin-credentials
      name: PGADMIN_DEFAULT_EMAIL
      property: PGADMIN_DEFAULT_EMAIL
    - key: /K8s/Clusters/Prod/pgadmin-credentials
      name: PGADMIN_DEFAULT_PASSWORD
      property: PGADMIN_DEFAULT_PASSWORD