apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Replace this with your NFS StorageClass name if different
  storageClassName: nfs
