apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-tls
  namespace: cert-manager
spec:
  secretName: pgadmin-prod-cert-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'pgadmin.vndprojects.com'